#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Resource", IsApplication=true)]

namespace WeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int cpb_animationDuration = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int cpb_color = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int cpb_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cpb_textColor = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int cpb_zoomInScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cpb_zoomOutScale = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int height_weight = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int use_gradient = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int width_weight = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int op_menu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int round_button = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int Log_button = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int Start = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int action_settings = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int action_settings1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int action_settings2 = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int imageView1 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int inputText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int listView1 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int logCity = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int logTemp = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int weatherIcon = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LogList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RowLog = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int Log = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircularPulsingButton = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 3
			public const int CircularPulsingButton_cpb_animationDuration = 3;
			
			// aapt resource value: 0
			public const int CircularPulsingButton_cpb_color = 0;
			
			// aapt resource value: 4
			public const int CircularPulsingButton_cpb_text = 4;
			
			// aapt resource value: 5
			public const int CircularPulsingButton_cpb_textColor = 5;
			
			// aapt resource value: 2
			public const int CircularPulsingButton_cpb_zoomInScale = 2;
			
			// aapt resource value: 1
			public const int CircularPulsingButton_cpb_zoomOutScale = 1;
			
			public static int[] loader_view = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int loader_view_height_weight = 1;
			
			// aapt resource value: 2
			public const int loader_view_use_gradient = 2;
			
			// aapt resource value: 0
			public const int loader_view_width_weight = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
