#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Resource", IsApplication=true)]

namespace WeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int cpb_animationDuration = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int cpb_color = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int cpb_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cpb_textColor = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int cpb_zoomInScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cpb_zoomOutScale = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int height_weight = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int use_gradient = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int width_weight = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int op_menu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int round_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Settings = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int ForecastIcon = 2131034123;
			
			// aapt resource value: 0x7f05001e
			public const int Log_button = 2131034142;
			
			// aapt resource value: 0x7f050004
			public const int Start = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int forecastDate = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int forecastTemp12 = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int forecastTemp18 = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int forecastTemp6 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int forecastTime12 = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int forecastTime18 = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int forecastTime6 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int forecastView = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int imageView1 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int inputText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout10 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout11 = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout3 = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout4 = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout5 = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout6 = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout7 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout8 = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout9 = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int listView1 = 2131034112;
			
			// aapt resource value: 0x7f05001c
			public const int logCity = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int logTemp = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int settings_button = 2131034141;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int weatherIcon = 2131034138;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LogList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RowForecast = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RowLog = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int Log = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int LogDBtoString = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int currentToast = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int emptyLog = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int enterCity = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int errorDB = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int error_message = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int log = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int netError = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int prop1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int prop2 = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int selectDC = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int settings = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int settingsTite = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int start = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircularPulsingButton = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 3
			public const int CircularPulsingButton_cpb_animationDuration = 3;
			
			// aapt resource value: 0
			public const int CircularPulsingButton_cpb_color = 0;
			
			// aapt resource value: 4
			public const int CircularPulsingButton_cpb_text = 4;
			
			// aapt resource value: 5
			public const int CircularPulsingButton_cpb_textColor = 5;
			
			// aapt resource value: 2
			public const int CircularPulsingButton_cpb_zoomInScale = 2;
			
			// aapt resource value: 1
			public const int CircularPulsingButton_cpb_zoomOutScale = 1;
			
			public static int[] loader_view = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int loader_view_height_weight = 1;
			
			// aapt resource value: 2
			public const int loader_view_use_gradient = 2;
			
			// aapt resource value: 0
			public const int loader_view_width_weight = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
